sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: OgUfYGz17u7e077OLuFnBU5b5rdkuUxezaVkGrvCbBA/tZfk5Lhk1j6nRU6aPNNWK96ZpMlBghSpw8qjVurugya6xfDj/EeawpWHjtx0j6gDyaZKoGxtyyqnBDANsUqTYHDD18XgAquxpLTNnGkkaB8N5xS/kaJX/qIlxWOhQuEbkDh9qBwgn/lwlzY72j5/qJ0dYrKnsXwsPO3JVITSck5C3TQkVCurSmVy3kAi8NdzcooPJq6MaP00EzecwiJ82rxBa3dYLzqKByg61yYsnlki+kdxBvpHIcTBsygSHVXLiuGYHnMF6VuGIJNMRwEIGDm0eVtMCL1pCBG7Fp6y+Oaxz3iJIbN+lypoauDG2U1wGulkhx1zBQkH/KcoaqfEPag/ymkWiDTinVJbvPvrytl2BOcd2ryw6SDh49ByMRTa+NjywugNUIrppmkr8jmgahG/XxL4+NP/JrUeGk3kbbHENK9hiceEghSutAxNVFaG6PrLZluGvWXoaZ/Rcle55cyUAH5uy3GefQkwEbwQ53cb4Jf65Jn8bMo4utBJk9IJ4okjwzK6Gywk2Cgj8nXrqQ7tH8ICmzSTD2jaB/Sfq3hAg4TWoNRtNQZAzGQifbpPwr4yl1fGWaADnjHWJ+7e1QX1B2VnJsqEr/y5NiR33Ytwi2fx6oKfH0bw0JgRmgs=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Boy-Allies-with-Uncle-Sam-s-Cruisers_6072
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy